package uno.d1s.security.autoconfiguration

import org.springframework.boot.context.properties.EnableConfigurationProperties
import org.springframework.context.annotation.Configuration
import uno.d1s.security.properties.SimpleSecurityConfigurationProperties

@Configuration
@EnableConfigurationProperties(SimpleSecurityConfigurationProperties::class)
public class ConfigurationPropertiesAutoConfiguration